### ISSUE TITLE
Make Scroll Wheel velocity More Configurable

### ISSUE THREAD

**Issue by Dwaynekj** [fin-hypergrid/core#290]
See discussion here https://github.com/fin-hypergrid/core/issues/282

**Comment by Dwaynekj** [comment]
The logic can be found here https://github.com/fin-hypergrid/core/blob/master/src/features/ThumbwheelScrolling.js

**Comment by hugoeanogueira** [comment]
Hey! I've been doing some work to make mousewheel scrolling speed more configurable :p
I've tracked the feature to `finbars` dependency (didn't see anything being triggered in `ThumbwheelScrolling.js`).

Two new properties were added `scrollingHorizontalMouseWheelMultiplier` and `scrollingVerticalMouseWheelMultiplier`, which are proxied to `finbars`.

These values can be set as:
- between 0 and 1 -> decrease speed;
- 1 -> original speed (default value);
- above 1 -> increase speed;
- a modulo is applied to negative values;

I'll open pull requests for both repositories for you to test and comment.
Thanks!

**Comment by hugoeanogueira** [comment]
The PRs:
- [finbars](https://github.com/openfin/finbars/pull/2)
- [fin-hypergrid](https://github.com/fin-hypergrid/core/pull/620)

**Comment by Dwaynekj** [comment]
@hugoeanogueira Did you test on Windows and Mac? Additionally, any thoughts into delegating the event from the ThumbwheelScrolling feature chain as opposed to from the finbars.

**Comment by hugoeanogueira** [comment]
Not yet, I need to get a Windows machine first and do some testing.
I've tried to do some debugging in ThumbwheelScrolling.js, but haven't managed to see any action in there. Maybe I have to configure anything for the event to be propagated to the ThumbwheelScrolling feature chain?

**Comment by joneit** [comment]
Resolved by **Hypergrid v2.1.11** (PR #722).
