### ISSUE TITLE
Unit Tests AND TypeScript

### ISSUE THREAD

**Issue by Dwaynekj** [fin-hypergrid/core#520]
Hypergrid is inheritantly very state-full, 100% UI oriented. As a first past at unit tests, we would like to be able to have API shape tests (more or less like a rudimentary type system). 

Here is our running example https://github.com/openfin/fin-hypergrid/blob/master/test/SelectionModel-tests.js

**Comment by Dwaynekj** [comment]
Or Maybe... its simpler to switch to Typescript with ES6+ Support

**Comment by jjrv** [comment]
One vote for TypeScript from here! I think the only existing alternative to Hypergrid in terms of features and licensing is [dgrid](http://dgrid.io/) from Dojo and they're currently rewriting it in TypeScript. Note that a rewrite isn't necessary for the language switch, they're doing it to get rid of other old dependencies.

**Comment by jjrv** [comment]
Note that this should really be: TypeScript AND unit tests. Switching to TypeScript gives you type checking and autocompletion right in the IDE, and mousing over a method call pops up a tooltip with JSDoc comments so it makes working with a large internal and external API a lot easier.

This eliminates a lot of bugs already when writing code and guarantees that many of the API calls are correct, but you still also need more unit tests for 3rd parties to make pull requests with confidence that they didn't break anything.

TypeScript will definitely also help with writing and maintaining the unit tests. If the API changes, the tests won't just fail... They won't compile and the IDE will highlight the offending code.

I could do a little prototyping work if you need convincing or a small case study for switching to TypeScript.

**Comment by Dwaynekj** [comment]
@jjrv Thanks for the input! Yes a prototype would definitely help. @joneit and I are new to Typescript (although we have other teams at openfin using Typescript). A case study could help us understand the scope of work to be done

**Comment by jjrv** [comment]
I could port the `sparse-boolean-array` npm package and `src/lib/SelectionModel.js`. This would show the entire toolchain and distribution for one package, using it from HyperGrid and porting a single HyperGrid internal class without touching the rest.

So the case study would cover using an external module written entirely in TypeScript, and doing a port piece by piece. Would that make sense?

**Comment by Dwaynekj** [comment]
That sounds perfect! Thanks so much.
Judging from our codebase. Do you think a major rewrite to Typescript could be accomplished by 1 person in a 3 week sprint?

**Comment by jjrv** [comment]
I think it could. It depends on how many architectural changes are done. For example the npm packages `extend-me` and `overrider` duplicate and extend ES6 functionality. Replacing everything with ES6 syntax or getting the old syntax to play nice with type inference may require some rethinking.

**Comment by jjrv** [comment]
Support for mixins should be landing to stable TypeScript this month, which will help in using a standardized syntax for them in HyperGrid.

**Comment by Dwaynekj** [comment]
Merging into another ticket
