### ISSUE TITLE
Column & Row Header Grouping

### ISSUE THREAD

**Issue by taewan-gtone** [fin-hypergrid/core#608]
Is it available grouped multi-column header and multi-row header? Where can I find example?

```
-----------------------------
           Col 1
-----------------------------
   sub 1     |        sub 2
-----------------------------

and

-----------------------------
|            |              |      
|            |      sub 1   |   
|Row 1       ----------------
|            |      sub 2   |
|            |              |
-----------------------------
```

**Comment by Dwaynekj** [comment]
@taewan-gtone We don't currently have an example of how to create multi-row header but if you look at the http://cdn.openfin.co/download/fin-hypergrid-addons.zip example code we have here you can see our grouped header example

**Comment by taewan-gtone** [comment]
Thanks.
How about multi-column header?

**Comment by Dwaynekj** [comment]
That should be in the link
