### ISSUE TITLE
Grouped Headers using Hypergrid Schema

### ISSUE THREAD

**Issue by eibertek** [fin-hypergrid/core#609]
Im having a problem with the plugin, beacuse im using the schema option in hypergrid instantiation.
In the demo its not used like this so my quesiton are:
- is there a demo with schema?
- the specific problem I have right now its when i set the headers, the parent header text is not centered.
- is there a function like:
   grid.setSchema({
    field:'header1', name:'header1',
    field:'header2', name:'header2',
    field:'header3', name:'subrow|header3',
    field:'header4', name:'subrow|header4',
    field:'header5', name:'subrow|header5',
    })

Thanks!!

**Comment by eibertek** [comment]
@joneit

**Comment by Dwaynekj** [comment]
@eibertek I'm assuming your referring to v2.0.2 using the grouped header demo [here](http://cdn.openfin.co/download/fin-hypergrid-addons.zip)

You can pass in the the schema in an options object with any setData [call])(https://github.com/fin-hypergrid/core/blob/master/src/Hypergrid.js#L814) or directly with or assigning to `grid.behavior.dataModel.schema` explicitly (which is a [setter](https://github.com/fin-hypergrid/core/blob/master/src/dataModels/JSON.js#L710)
