### ISSUE TITLE
First character is wrongly mapped for non-US keyboards when opening the cell editor (editOnKeyDown=true)

### ISSUE THREAD

**Issue by hugoeanogueira** [fin-hypergrid/core#621]
**Description**
When using the keyboard to open cell editor, by start typing a visible character, some characters may not be correctly mapped in the `charMap` from `Canvas.js` when the user is using a keyboard layout different from the US (e.g. portuguese layout).

**Test conditions**
OS: Mac OS v10.12.6
Browsers: Chrome 60.0.3112.113 and Firefox 55
Keyboard layout: Portuguese

**How to reproduce**
- Set the portuguese keyboard layout in OS settings (e.g. mac);
- Open hypergrid's demo app;
- Select an editable cell with a simple click (cell must stay active, with editor closed);
- Type `_` (I think it corresponds to SHIFT + 0) multiple times;
- Check if all the typed characters are the `=`, e.g. `====`, or if a wrong character was typed in the beginning like this `)===`.

**Demo**
- [PT keyboard](https://user-images.githubusercontent.com/4893840/29754041-abe2477c-8b75-11e7-858f-4ea05682f661.gif)
- [US keyboard](https://user-images.githubusercontent.com/4893840/29754043-b07b5b66-8b75-11e7-83cb-27e9b754c0cc.gif)

**Comment by joneit** [comment]
Resolved by **Hypergrid v2.2.11** (PR #722).
