### ISSUE TITLE
Space key does not open cell editor

### ISSUE THREAD

**Issue by hugoeanogueira** [fin-hypergrid/core#623]
**Description**
When using the keyboard to start cell editor, we cannot use the space key to open the cell editor and replace its content with a new space character.
Everything works fine if we type a "normal" character.

**Test conditions**
OS: Mac OS v10.12.6
Browsers: Chrome 60.0.3112.113 and Firefox 55

**How to reproduce**
- Open hypergrid's demo app;
- Focus on an editable cell (either with or without content);
- Hit the "space" key (nothing happens -> should have opened the editor);
- Hit the "a" key (a new editor with "a" value type should be rendered).

**Comment by joneit** [comment]
Resolved by **Hypergrid v2.2.11** (PR #722).
