### ISSUE TITLE
grid repositioning after tab/enter

### ISSUE THREAD

**Issue by frankiehf** [fin-hypergrid/core#628]
Hello,
i noticed in the demo that if you try to edit a cell and then press tab or enter,the grid moves to the right, up to the point that you cannot see the selected cell anymore. is there a function that defines the repositioning of the grid/ scrollbar thumb on pressing tab/enter?
to replicate the issue,just go on the demo page https://fin-hypergrid.github.io/core/2.0.2/
open the dashboard, select "set data 1",edit a cell and press enter. The selected cell wont be visible anymore,and tab wont work.
I also noticed that if you select a cell towards the end of the grid, with no chance for the grid to move  forward,both enter and tab work as planned.

**Comment by Dwaynekj** [comment]
@hugoeanogueira @joneit Is this something you guys noticed in the PR your evaluating?

**Comment by frankiehf** [comment]
any news on this? thanks in advance

**Comment by frankiehf** [comment]
solved by myself using this comment:
https://github.com/fin-hypergrid/core/issues/519#issuecomment-303113542
