### ISSUE TITLE
rendering context menu for grid column header

### ISSUE THREAD

**Issue by vikrametc** [fin-hypergrid/core#631]
Hi Team,
Could you please let me know how can I render dropdown on right click of grid cell.
Basically I want user to perform some action on grid cell by right click.

1.When user right clicks the grid, I need to show them bunch of actions to be performed. Please help me how can I do that.

2. Other thing I want to know is, how can I add/remove columns in the grid dynamically?

It will be helpful if you can provide the sample syntax too.

**Comment by Dwaynekj** [comment]
Hello Vikrametc,

### Events

You can listen to events with grid.addEventListener, [see](https://github.com/fin-hypergrid/core/blob/c987a4d864778045c6f26c3c905e774db0a7ae79/demo/js/demo/events.js#L10), which will provide absolute position of the mouse from which you can create a div / container and position.

You also have the option to use the feature Chain if you want it to be launched before any particular native hypergrid event handler. [See](https://github.com/fin-hypergrid/core/blob/9e8bdf922f142ba597303d50369a275a3d8279d2/src/behaviors/JSON.js) you can create a feature like [this
](https://github.com/fin-hypergrid/core/blob/9e8bdf922f142ba597303d50369a275a3d8279d2/src/features/CellEditing.js#L17) that implements handleDoubleClick and have it respond to an event in order it is put in the features array.

### Columns
The quick and dirty way is to call behavior.hideColumns but to actually remove a column you would need to call grid.setData with your data having been prior manipulated to have that column missing.
This is more in line with the grid being a renderer that only displays and doesn't manipulate the dataset. Its a fast renderer where sending it changes to a dataset with a column missing should be neglible

**Comment by vikrametc** [comment]
Than you Dwayne,

Can you please let me know how can I get the absolute position from the
custom event which got fired in grid on right click.

When I debug, I didn’t find any.

Vikram

**Comment by Dwaynekj** [comment]
It should be `e.detail.mousePoint`

**Comment by vikrametc** [comment]
Hi Dwayne,

I am able to show the component at mouse click position.

I see another issue now,
I check whether user click on the header of grid by event.detail.gridcell.y
===0.

When I am not overlapping my component I am getting this value as 0 for
column header.

But when the component is overlapped, the event is not giving me proper
value.

It gives Gridcell.Y equal to 0 even though if click in the middle of the
grid.

Do you know how to get the correct click X and Y position in this case?

Vikram

**Comment by vikrametc** [comment]
I always gets X as -2 and Y as 0 no matter where I click in the grid

Vikram

**Comment by vikrametc** [comment]
Never mind, I got it wrong.
