### ISSUE TITLE
 src="fin-hypergrid.github.io/core/build/2/fin-hypergrid.js getting 404 error where can i download this file

### ISSUE THREAD

**Issue by RajendraOpenFin** [fin-hypergrid/core#632]
where can I download fin-hypergrid.js file

**Comment by dcchuck** [comment]
Hypergrid available as a node module on NPM [here](https://www.npmjs.com/package/fin-hypergrid). 

Pre-built versions for inclusion in a script tag are hosted via the gh-pages branch of the core repo. You can copy the tags from the index page https://fin-hypergrid.github.io/ or access the builds directly on the gh-pages branch [here](https://github.com/fin-hypergrid/core/tree/gh-pages). It's in the version number/build directory.
