### ISSUE TITLE
ColumnSorting feature sends the wrong column index if there are hidden columns

### ISSUE THREAD

**Issue by nmichaud** [fin-hypergrid/core#670]
This should use the index from the currently visible columns:

https://github.com/fin-hypergrid/core/blob/master/src/features/ColumnSorting.js#L24

**Comment by nmichaud** [comment]
Something like this:

var column = grid.behavior.getActiveColumn(event.gridCell.x);
grid.fireSyntheticColumnSortEvent(column.index, event.primitiveEvent.detail.keys);

**Comment by joneit** [comment]
As discussed, not a bug: The event data always refers to the “grid” (_i.e.,_ visible or active) column index. The `getActiveColumn` Call should be in the handler. Closing…
