### ISSUE TITLE
Fix passive event listener warning in Chrome

### ISSUE THREAD

**Issue by LukeSheard** [fin-hypergrid/core#673]
In Chrome Hypergrid generates a lot of non-passive event listener warnings from the scroll events which can be added to Hypergrid from 

```javascript
container.addEventListener('wheel', this._bound.onwheel);
```

in `index.js`. I haven't been able to locate the corresponding code in the repo, so I'm not sure if this has already been patched though. Adding `{ passive: true }` as a last argument will squash this warning. 

See https://www.chromestatus.com/feature/5745543795965952 for context.

**Comment by joneit** [comment]
@LukeSheard Thanks for bringing this to our attention. Will address for one of the forthcoming versions 2.1.0 & 3.0.0, both expected to be released this month.

**Comment by G-S-Paris** [comment]
Has this been addressed? I'm not able to see anything about it in the changelist
