### ISSUE TITLE
Possible bug in core testbench file name

### ISSUE THREAD

**Issue by lancelab** [fin-hypergrid/core#692]
File must be renamed to
cellEditors.js
in
https://github.com/fin-hypergrid/core/blob/master/demo/js/demo/celleditors.js

otherwise
gulp browserify-demo
fails

because it is called with:
initCellEditors = require('./cellEditors'),
in index.js

**Comment by joneit** [comment]
Thanks, I've edited the path in index.js in the v2.1.4 branch (rather than renaming the file).
