### ISSUE TITLE
Errors in testbench demos

### ISSUE THREAD

**Issue by lancelab** [fin-hypergrid/core#693]
Reproduced on
Version 55.0.2883.75 (64-bit) Linux

![2 1 2---error1---screenshot at 2018-02-07 16 09 14](https://user-images.githubusercontent.com/368709/35944542-6b2d269c-0c22-11e8-866a-80f9f9bca9a6.png)
![2 1 0---error2---screenshot at 2018-02-07 16 11 44](https://user-images.githubusercontent.com/368709/35944553-73d8ada2-0c22-11e8-8671-a3fbce8c7825.png)
![2 1 0---error2----screenshot at 2018-02-07 16 11 18](https://user-images.githubusercontent.com/368709/35944559-79fd53fe-0c22-11e8-9a53-26e4141f4143.png)

![2 1 2-error1--screenshot at 2018-02-07 16 09 48](https://user-images.githubusercontent.com/368709/35944517-4f32bcae-0c22-11e8-8cf0-d321fc97e94b.png)

**Comment by joneit** [comment]
Thanks for forwarding these.
1. Fixed in 2.1.3 (released this morning).
2. Fixed in 2.1.2 release.
3. Same as #2.
4. Same as #1.
