### ISSUE TITLE
Column auto sizing is only applied when the cursor hovers the grid for the first time

### ISSUE THREAD

**Issue by nclsclsn** [fin-hypergrid/core#710]
I'm running a single page application and I'm creating a new grid each time i'm clicking on a different link of my navigation toolbar.
Today I have upgraded from 2.1.0 to 2.1.6.
Before the upgrade, the grid was properly rendered with the column size automatically calculated. Now the auto sizing gets in effect only when I hover the grid with my cursor.
I haven't changed my code and I am still calling grid.takeFocus() after initialization.

I have gone through the release notes but can't get my head around what change could have updated this behavior.
Any idea what could be happening?
Thanks in advance for your insight!

**Comment by joneit** [comment]
Nicolas,

Thanks again for your feedback.

These very simple examples seem to auto-size their columns:
* https://fin-hypergrid.github.io/core/2.1.6/example.html (calls `setData`)
* https://fin-hypergrid.github.io/core/2.1.6/multiple-grids.html (uses `data` option)

Please compare your code with the code in the examples' `<script>...</script>` elements. See if you can reduce your code to the simplest possible example that fails and post it here.

I agree it would be better if it worked as it did before. I'm not sure what changed. Try this at end of your set up script:
```js
setTimeout(function() {grid.behaviorChanged();});
```
I do recall [removing a `setTimeout`](https://github.com/fin-hypergrid/core/compare/v2.0.2...v2.1.6#diff-74c9cc064dae84ce7ea9d4f3d376bc07L84) call from the testbench, _i.e.,_ the demo, not the core code; and it was _removed,_ not added.

**Comment by joneit** [comment]
@nclsclsn fyi edited previous comment `behaviorChanged` -> `behaviorShapeChanged`. Please let me know if calling `grid.behaviorShapeChanged()` (even if just in the console) addresses this issue. If will see if it can be added to core code.... J.

**Comment by nclsclsn** [comment]
Hi Jonathan,

Thanks for your suggestion.
The setTimeout solution didn't work out for me but I've found another way to auto size the columns immediately.

I am receiving row information from a websocket and I'm then calling:
                    self.grid.behavior.dataModel.addRow(row);
                    self.grid.behavior.reindex();
                    self.grid.behaviorChanged();

With only these, I need to hover on the grid for the columns to automatically resize.

If I had this extra line:
                    self.grid.canvas.paintNow();
I can observe immediate resizing.

This discovery is consistent with this release note from 2.1.2:
Internal: Reorganized the way the new deferred behavior changes were implemented to make sure they are resolved at the next grid render.
And i've double checked that I was indeed observing the same problem when migrating from 2.1.0 to 2.1.2.

I don't think my solution is the most performant one but it works and I'm fine living with that until HyperGrid 3.0.

**Comment by joneit** [comment]
Nicolas, ok I'm going to close this issue for now.... but it would still be useful if you could post a minimal example where this fails so I can get to the bottom of it. thx J

**Comment by nclsclsn** [comment]
I've tried to do a minimal example without Angular and websocket but i can't come up with something that triggers the issue.
I will in any case revisit my implementation fully when HyperGrid 3.0 is out and I will monitor if it is still happening.

**Comment by nclsclsn** [comment]
Brilliant, it works fine, thanks!
