### ISSUE TITLE
Broken dep in package-lock.json

### ISSUE THREAD

**Issue by rapzo** [fin-hypergrid/core#711]
Not an issue per se, but just so everyone knows, `package-lock.json` was generated with `synonomous` pointing to a symlink/linked package.

Prolly not worth the PR, but i'd gladly do it if you guys want it.

**Comment by joneit** [comment]
Thanks @rapzo for the feedback! I noticed this last night much to my chagrin. Already taken care of in my 2.1.7 branch — to be released probably by EOD tomorrow if not today.

**Comment by rapzo** [comment]
Sweet! Thanks!
