### ISSUE TITLE
Vertical layout?

### ISSUE THREAD

**Issue by timkpaine** [fin-hypergrid/core#723]
Is there any ability to configure the chart so the header columns are vertical? I.e. the normal horizontal layout looks like 
<img width="653" alt="screen shot 2018-06-05 at 12 34 58 am" src="https://user-images.githubusercontent.com/3105306/40955566-d5db319a-6858-11e8-8f60-bdf12c3188fe.png">

And i'm looking for something like:a
<img width="105" alt="screen shot 2018-06-05 at 12 41 01 am" src="https://user-images.githubusercontent.com/3105306/40955694-8c832394-6859-11e8-9a4e-62df076fe156.png">

**Comment by joneit** [comment]
@timkpaine This would require an alternate grid renderer, which is not huge, although there will be ripple effects with other parts of code that assume y is rows and x is columns. So this would be opening a whole can of worms. That said, this would certainly be a worthy feature...!

Have you considered:
1. making the headers an actual row
2. subclassing the data model to transpose the data on the fly
3. set the first column (no the headers) as fixed (non-scrolling)

Another thing we could more easily do is rotate the headers _n_° (_e.g., n_ = 45 or _n_ = 90).

JE
