### ISSUE TITLE
Error in terminate()

### ISSUE THREAD

**Issue by deviousasti** [fin-hypergrid/core#733]
```
            terminate: function() {
                document.removeEventListener("mousedown", this.mouseCatcher),
                this.canvas.stop(),
                y.grids.splice(this.grids.indexOf(this), 1)
            }
```
`this.grids` is undefined.
If the objective is to remove the grid from the global list of grids,
shouldn't the last line be `y.grids.splice(this.grids.indexOf(this), 1)`.

**Comment by joneit** [comment]
Good catch thanks. Obviously method had never been tried! Will be fixed in next patch release v2.1.15 (PR #735, commit b6fce08).
