### ISSUE TITLE
License is misleading

### ISSUE THREAD

**Issue by mofojed** [fin-hypergrid/core#743]
In `package.json`, it indicates this project is using the MIT license.

However, in the `LICENSE` file, it is an OpenFin license, which looks the same as MIT license but with the added clause:

```
You may not redistribute the software or modifications as part of any
application that can be described as a development toolkit, library or
framework.
```

This is very misleading. Since many people will import packages through npm and pull the licenses from `package.json`, they could think it is just an MIT license, when it is in fact not. `package.json` should be updated to indicate this is NOT MIT license.

**Comment by joneit** [comment]
The MIT license provides space for custom restrictions. I guess it is more accurately a "modified MIT license."

In any case, after some internal discussion, we have decided to remove the clause in its entirety (PR #766, to be included in the `3.1.0` release).
