### ISSUE TITLE
Can column widths be auto-fitted to canvas size?

### ISSUE THREAD

**Issue by RandomGHUser** [fin-hypergrid/core#744]
If I have a grid width of 1000px, is there a way for hypergrid to dynamically resize columns to take up the entire space of the grid, and recalculate on canvas resize?

Other grids (such as slickgrid) will do this, and will only display horizontal scrollbars when the entire grid width is less than each cell's minimum width.

Apologies if this has already been discussed, I'm seeing a lot of broken issue links and tutorial links.

**Comment by joneit** [comment]
There is no setting for this but you might try:
1. `grid.addEventListener('fin-grid-resized', fn)` and in your `fn`:
2. iterate through active column list (`grid.behavior.colums.forEach()`)
3. calling `grid.beahvior.setColumnWidth()` on each column

**Comment by RandomGHUser** [comment]
Seems to work well, thank you.   I will build a function that will give me the functionality I'm looking for.

**Comment by joneit** [comment]
Cool. closing...
