### ISSUE TITLE
How to manipulate scrollbar style / position?

### ISSUE THREAD

**Issue by RandomGHUser** [fin-hypergrid/core#746]
Is there a way to change the scrollbar look / position (even set it to the browser default, showing on the side of the grid?)

By default, it is a mostly-transparent hover over the grid itself, the header, and does not have arrows at the ends, which makes it difficult to see and scroll.

There have been many topics on this in the past, and a couple regarding enhancing the documentation (does that mean this functionality already exists?):

https://github.com/fin-hypergrid/core/issues/549
https://github.com/fin-hypergrid/core/issues/548

I've found a couple undescribed string variables possibly related to styling under the documentation:
https://fin-hypergrid.github.io/core/doc/module-defaults.html

vScrollbarClassPrefix
hScrollbarClassPrefix

Not quite sure what these do, they don't seem to tie into a normal class.

Any help is appreciated.

**Comment by RandomGHUser** [comment]
Still unsure about how to do this, is there any documentation?  I'd rather disable the custom scrollbar and use the standard system scrollbar if possible.

**Comment by joneit** [comment]
Yes, it lacks documentation, but it is completely configurable, both in appearance and positioning.

I will write up documentation and have _something_ up there by Monday. 

The API does not include arrows but I will show you how to create your own. 

No, you cannot use the system scrollbars, because the grid is actually never larger than what you see. (It is re-drawn on every animation frame.)

**Comment by RandomGHUser** [comment]
Thank you, I am looking forward to it...when the documentation is posted, could you provide a link?

**Comment by RandomGHUser** [comment]
Another request for the scrollbar usage - when mousedowning somewhere along the scrollbar area (but not directly on the scroller itself), the behavior currently acts as if I am holding the scroller, and moving up or down will scroll the page.   

Is there a way to have this behavior modified to act like a typical scroller (where the behavior would be to continually scroll the grid until mouseup or until the scroller is under the mouse cursor)?  I've also noticed that the mousedown event will sometimes "stick" if I move out of the grid canvas area before releasing, so when moving the mouse back over the canvas, it believes I'm still in the mousedown state.

**Comment by joneit** [comment]
Hey good morning, been out of sorts, but yes I will have this done by EOD today!

**Comment by RandomGHUser** [comment]
When you're able to get the scrollbar documentation done, please confirm, thanks again

**Comment by RandomGHUser** [comment]
Squeaky wheel here, checking the status...

**Comment by joneit** [comment]
As you may have noticed, the release notes for Hypergrid 3.0.3 mention scrollbar tutorial, which you can find [here](http://fin-hypergrid.github.io/core/demo/formatter-workbench/?p=26).
