### ISSUE TITLE
How do you hide a row?

### ISSUE THREAD

**Issue by nowherenearithaca** [fin-hypergrid/core#748]
I can see how to hide columns, and how to set row background colors, but it's not clear how to hide/show specific rows.

**Comment by joneit** [comment]
Rows cannot be "hidden"; it is up to the data model to maintain the set of rows. One way to do this is to have a data model with a subclass that maintains its own `data` array, based on an `index` array that maps visible rows from the superclass's `data` array. Take a stab at it and let me know if you get stuck.

**Comment by nowherenearithaca** [comment]
thx - will do

**Comment by joneit** [comment]
I just released [`datasaur-indexed@3.0.0`](https://www.npmjs.com/package/datasaur-indexed/v/3.0.0). It does what I prescribed above but was out of date. It is now compatible with Hypergrid 3.0 so you can use it.

**Comment by nowherenearithaca** [comment]
thx for letting me know - still familiarizing myself with things in general as I can - I know the things I want to do, it's just a matter of mapping that to your implementation of everything.
