### ISSUE TITLE
RowResizing will be implemented? 

### ISSUE THREAD

**Issue by MTeres** [fin-hypergrid/core#750]
I would like to know if 'RowResizing' will be implemented?
In the current state what are the blocking points for this feature?
Currently this feature is commented and looking at the implementation seems not ready for that yet.

Thanks!

**Comment by joneit** [comment]
Thanks, Marcus, for bringing this up. You are referring to UI row sizing, which was a _feature_ that worked in the original version. Not sure when or why it got turned off. I will discuss with the team about resurrecting it for `3.1.0` (end of Sept.) and let you know.

In the meantime, be aware that rows can be programmatically sized with [`setRowHeight`](https://fin-hypergrid.github.io/core/doc/Hypergrid.html#setRowHeight) and interrogated with [`getRowHeight`](https://fin-hypergrid.github.io/core/doc/Hypergrid.html#getRowHeight).

**Comment by MTeres** [comment]
Ok, I will wait for the feedback!
Thanks again.
