### ISSUE TITLE
TypeError: Cannot read property 'getRowCount' of null at Constructor.getRowCount using newer version Fin- Hypergrid 3.0.1 version

### ISSUE THREAD

**Issue by Revathigb** [fin-hypergrid/core#757]
Hi, 
In my angular app when Hypergrid is created getting bunch of type errors like cannot read propety 'getRowCount','getLogicalRowCount' etc,

Note: Didn't face this issue in older version Hypergrid 2.0.3 after upgrading Fin-hypergrid version 3.0.1 getting  above mentioned errors.

 Can anyone help me to fix this?

**Comment by joneit** [comment]
@Revathigb is this still an issue for you? because I see you've submitted #758 suggesting you've moved beyond this error. please either close the issue or confirm with a comment if it is still an issue.

**Comment by Revathigb** [comment]
This issue is not resolved.When a hypergrid is created.I get these errors even after hypergrid is initialize.

**Comment by joneit** [comment]
@Revathigb We need a bit more to go on here. Please reduce the errant use case to a minimal-demonstrable along the lines of example.html ([demo](https://fin-hypergrid.github.io/core/demo/example.html), [github](https://github.com/fin-hypergrid/build/blob/master/demo/example.html)).

**Comment by joneit** [comment]
On phone we determined this was result of forcing a render before columns created.

We are investigating the "etc." (other errors).

Created Issue #765:
`renderLastSelection` throws error when no rows
