### ISSUE TITLE
Hypergrid 3.0.1 showcheckbox

### ISSUE THREAD

**Issue by Revathigb** [fin-hypergrid/core#758]
When a new row is added to the hypergrid,If a row is checked it selects all the rows in the hypergrid.
Unable to  deselect the checkboxes. 
After refreshing the app the checkbox select or unselect works. 
Need help to resolve this issue :)

Thanks

**Comment by joneit** [comment]
I'm not seeing this behavior. How are you adding rows? Did you call `myGrid.behaviorShapeChanged()` ?

**Comment by Revathigb** [comment]
I'm adding dynamically using form and for behaviourchange I'm using grid.behaviorChanged();

**Comment by joneit** [comment]
If you could forward a minimal-demonstrable example, please, I would then be able to determine if a fix could be made. thanks

**Comment by joneit** [comment]
Thanks for the screenshare. As we identify real issues, I will create separate GitHub issues for each.

Created Issue #764:
When all rows selected, `getSelectedRows` returns inaccurate results.

**Comment by joneit** [comment]
Created Issue #765:
renderLastSelection throws error after deleting all rows

**Comment by joneit** [comment]
Created Issues #769 and #770:
Hypergrid mouse events have outdated `keys`/`currentKeys`
Hypergrid `keys`/`currentKeys` not SHIFTed

**Comment by joneit** [comment]
All sub-issues resolved, for `3.1.0` release.

**Comment by joneit** [comment]
Thanks @Revathigb for reporting these bugs and the opportunity to track down these bugs and address them! Version `3.1.0` (formerly called `3.0.4`) will be released this week (possibly today).
