### ISSUE TITLE
Scrollbar enhancements/fix request

### ISSUE THREAD

**Issue by RandomGHUser** [fin-hypergrid/core#760]
~~When dragging the scrollbar, if leaving the grid element and releasing the mouse button, the grid does not detect it, and still believes that the mouse button is still down when hovering backing over the grid (so it will scroll even though the mouse button isn't down).~~ \[Moved to new [finbars Issue #6](../../finbars/issues/6)]

~~Also want to request the scrollbar functionality be enhanced to include a button (up/down/left/right) at each side of the scrollbar,~~ \[Moved to new [finbars Issue #4](../../fin-hypergrid/finbars/issues/4)] ~~and holding down a mouse button on the bar (not the thumb) will scroll the grid to that position incrementally.   These are standard scrollbar functions which do not seem to be currently implemented in hypergrid.~~ \[Moved to new [finbars Issue #5](../../finbars/issues/5)]

**Comment by joneit** [comment]
Hello @RandomGHUser, We appreciate your feedback. I am moving your second paragraph to a new ticket. In future please submit multiple issues as _separate_ tickets.

**Comment by joneit** [comment]
I am moving your first paragraph to [a new issue](../../finbars/issues/6) in the `finbars` repo.
