### ISSUE TITLE
correct this to make anonymous column calculator function work

### ISSUE THREAD

**Issue by slimtom95** [fin-hypergrid/core#784]
There is a tiny mistake on the latest master commit caused anonymous function not work for column calculator, and here it is:

core/src/behaviors/Column.js line 393
`    } else if (calculator.test(REGEX_ANON_FUNC)) {`
`calculator` is the function literal string, not an regex, this line should be
`    } else if (calculator.match(REGEX_ANON_FUNC)) {`

Correct this and it would work fine.

**Comment by joneit** [comment]
Thanks, good catch!

I will add to the the next release, which will likely be 3.2.1 and will likely be published on the weekend.
