### ISSUE TITLE
How to disable scroll bar style tag injection

### ISSUE THREAD

**Issue by slimtom95** [fin-hypergrid/core#789]
The custom scroll bar style with a .css works, except the `thumb`', like unable to set the `thumb`'s  background color.  After delete the injected style tag, my part of  `thumb` style css works.

I think there should be a way to disable the injection and the `thumb` style should be able to be overridden.

**Comment by joneit** [comment]
This is probably because the scrollbar stylesheet is injected right before the grid, which is probably _after_ your stylesheet. Try moving your stylesheet to the end of the body tag. I believe all stylesheets are parsed prior to building the DOM tree.

**Comment by joneit** [comment]
Alternatively, did you try marking your styles with `!important` ?

**Comment by joneit** [comment]
If you want to remove the injected stylesheet:
```js
body.removeChild(document.getElementById('injected-stylesheet-finbar-base'));
```
or replace it with your own:
```js
document.getElementById('injected-stylesheet-finbar-base').replaceWith(myStyleEl);
```

**Comment by slimtom95** [comment]
`!important` solved my issue, Thank you joneit :D
