### ISSUE TITLE
how i can break long line into two line in the cell .

### ISSUE THREAD

**Issue by khaled26** [fin-hypergrid/core#803]
for example , i have one long line , i want to break it to three lines and update the row height . 
is that possible ?

**Comment by joneit** [comment]
Anything is possible with a custom cell renderer:
1. Write your cell renderer function following SimpleCell.js for an example
2. Register the cell renderer using `myGrid.cellRenderers.add`
3. Set the `render` property of the cell/column/row/grid to the registered name

See [`renderMultiLineText`](https://github.com/fin-hypergrid/core/blob/master/src/cellRenderers/SimpleCell.js#L211-L259) in SimpleCell.js which wraps lines.

This function is only applied to header cells and only when said cells have a truthy `headerTextWrapping` property.

The reason for this restriction is to keep Hypergrid performant. Keep in mind however that although SimpleCell.js is widely used in applications, it was only ever intended as sample code. It demonstrates a lot of features while still being reasonably performant. Measuring text forward, and then backing up to the nearest previous word break, would not be performant if applied to every cell. That is why you really would only want to do this on cells that need it.

We could consider changing this, considering however that it is under a boolean prop. But we judged that it would inevitably lead to people turning the feature on for the entire grid and only noticing later that the grid is much slower but not being sure why. Again, SimpleCell was only meant as sample code, and we want to keep it performant. If you really want to do this, you can provide your own cell rederer.

Some things to note about `renderMultiLineText`:
* This function is not exposed so you will need to copy & paste it.
* This function does not respect embedded newline characters (`'\n'`). If you need this feature you will have to do some additional coding.

**Comment by khaled26** [comment]
Thanks jonathan .. it's really helped me to understand somethings that i wasn't aware . 
can you please explain step 3  ? (Set the render property of the cell/column/row/grid to the registered name) .. 
how i can do that in the code ? i didn't find any similar code like that .
